### ISSUE TITLE
Exception on app start

### ISSUE THREAD

**Issue by artur-beljajev** [internetee/rest-whois#27] opened 2016-12-21 02:10 UTC
I get the following exception unless I comment config/initializers/new_relic_app_name.rb#1:
https://gist.github.com/artur-beljajev/e3221bf9a00bbeb11090c63e77a2dac8.

I wonder how it works on prod.

P.S. I followed "Installation" guide from readme.

**Comment by teadur** [comment] 2017-01-26 15:32
Works for me following Installation guide from readme.
Sounds like you are missing newrelic gem.

**Comment by artur-beljajev** [comment] 2017-01-31 15:24
http://prntscr.com/e2prci new_relic gem is in Gemfile.

**Comment by teadur** [comment] 2017-02-01 10:06
Newrelic can be used only one way: https://rubygems.org/gems/newrelic_rpm/versions/3.15.2.317
Strange, i dont have the line you said commented and it works for me, something must be different in your deployment scenario, i would like to close the issue as cannot reproduce as it works for me.

**Comment by artur-beljajev** [comment] 2017-02-01 10:10
I will debug it.

**Comment by artur-beljajev** [comment] 2017-02-01 10:11
Do we use new relic at all?

**Comment by teadur** [comment] 2017-02-01 12:30
I dont know what you want to debug with the issue, yes we use newrelic.
I will close the issue as of from my perspective it's working as intended.

**Comment by artur-beljajev** [comment] 2017-02-17 13:23
The issue is still persisted. `new_relic_app_name` is now removed from `application-example.yml` since it is not used in any deployment.

**Closed** 2017-02-17 13:26 UTC
